### PR TITLE
Fix com interop for linux docker

### LINKED ISSUE #539: RazorEngine.Core.NetCore in a Linux docker container: 'COM Interop is not supported on this platform.'
Can you give me a slight insight what's happening here and why it tries to use Interop?

            var path = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);

            var templateManager = new ResolvePathTemplateManager(new[]
                {Path.Combine(path, EmailTemplatesFolder)});

            var config = new TemplateServiceConfiguration
            {
                TemplateManager = templateManager,
            };

            var templateService = RazorEngineService.Create(config);

           var body = templateService .RunCompile($"MyTemplate.cshtml", null, _myModel);

The template itself is quite simple:

    @model server.Models.MyModel

    <!DOCTYPE html>
    <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title>Welcome</title>
        @{ Model.Subject = "bla bla bla"; }
    </head>
    <body>
        <p>
            Hello @Model.Username,
        </p>
    </body>
    </html>

However when I run it on a remote Linux machine in a docker container I got the following error:

    RazorEngine.Templating.TemplateCompilationException: Errors while compiling a Template.
    Please try the following to solve the situation:
      * If the problem is about missing/invalid references or multiple defines either try to load 
        the missing references manually (in the compiling appdomain!) or
        Specify your references manually by providing your own IReferenceResolver implementation.
        See https://antaris.github.io/RazorEngine/ReferenceResolver.html for details.
        Currently all references have to be available as files!
      * If you get 'class' does not contain a definition for 'member': 
            try another modelType (for example 'null' to make the model dynamic).
            NOTE: You CANNOT use typeof(dynamic) to make the model dynamic!
        Or try to use static instead of anonymous/dynamic types.
    More details about the error:
     - warning: (7, 4) Unnecessary using directive.
    	 - warning: (6, 4) Unnecessary using directive.
    	 - warning: (8, 4) Unnecessary using directive.
    	 - warning: (5, 4) Unnecessary using directive.
    	 - error: (0, 0) Unexpected error writing debug information -- 'COM Interop is not supported on this platform.'

I'm using 4.6.0-rc1 version btw.

### PR DESCRIPTION
**Pull request by mgoodfellow**
Resolves: https://github.com/Antaris/RazorEngine/issues/539

### CODE REVIEW

**Comment by Wingjam** [comment]
@fouadmess Any chance of merging this?

**Comment by mgoodfellow** [comment]
Happy to upload a nuget of this build if you want? I currently this branched version as a nuget in our private MyGet feeds, but could put up a fixed version and unlist when its eventually merged?

**Comment by Wingjam** [comment]
@mgoodfellow I would really appreciate to have a nuget of this build if you can share!

**Comment by mgoodfellow** [comment]
@Wingjam will get this sorted for you first thing tomorrow morning (UK time) and link the nuget in here!

**Comment by Wingjam** [comment]
@mgoodfellow Thanks for taking the time

**Comment by mgoodfellow** [comment]
@Wingjam I've published it here: https://www.nuget.org/packages/RazorEngine.NetCore-LinuxDockerFix - as a sanity check, I've pulled it into our production deployments to make sure it behaves as expected.

**Comment by Wingjam** [comment]
@mgoodfellow Thanks a lot for your time! I will check this out. Im also looking into [RazorLight](https://github.com/toddams/RazorLight) which seems really more maintained

**Pull request merged**
